# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: 'Build.msbuild'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadSecureFile@1
  name: license
  displayName: 'Download'
  inputs:
    secureFile: 'license.xml'

- powershell: Move-Item -Path $(license.secureFilePath) -Destination .\lib\license.xml

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    vsVersion: '15.0'
    msbuildArgs: '/t:Versions /p:NoWarn=1591 /p:RunCodeAnalysis=true;CodeAnalysisRuleSet=..\..\Sitecore.FakeDb.ruleset'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/TestResult_*.xml'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'drop'
    publishLocation: 'Container'